services:
  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    restart: always

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/orcanet
    depends_on:
      - redis

  worker:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    command: celery -A celery_worker.celery_app worker --loglevel=info
    volumes:
      - .:/orcanet
    depends_on:
      - redis

  tailwind:
    build: .
    command: npm run watch
    volumes:
      - .:/orcanet
    tty: true
    stdin_open: true


  browsersync:
    image: node:18-alpine
    working_dir: /orcanet
    volumes:
      - .:/orcanet
    command: npx browser-sync start --proxy "http://web:5000" --files "app/static/css/*.css, app/templates/**/*.html" --no-open --no-ui
    ports:
      - "3000:3000"
    depends_on:
      - web
