services:
  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    restart: always

  web:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "5000:5000"
    volumes:
      - .:/orcanet
    depends_on:
      - redis

  worker:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    command: celery -A celery_worker.celery_app worker --loglevel=info
    volumes:
      - .:/orcanet
    depends_on:
      - redis

  tailwind:
    build: .
    command: npm run watch
    volumes:
      - .:/orcanet

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379