services:
  redis:
    image: "redis:7-alpine"
    restart: always

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/orcanet
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A celery_worker.celery_app worker --loglevel=info
    volumes:
      - .:/orcanet
    depends_on:
      - redis

  # --- NEW SERVICE FOR TAILWIND ---
  tailwind:
    build: .
    command: npm run watch
    volumes:
      - .:/orcanet
    working_dir: /orcanet
